version: '2'
services:
    helppopcorn-app:
        image: helppopcorn
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://helppopcorn-postgresql:5432/HelpPopcorn
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    helppopcorn-postgresql:
        extends:
            file: postgresql.yml
            service: helppopcorn-postgresql
